### ISSUE TITLE
Unavailable for your site because your domain is not properly configured to support HTTPS 

### ISSUE THREAD

**Issue by AbdelfattahAbouelaoualim** [AbdelfattahAbouelaoualim/dse.github.io#1]
Hello,
I created a static site with github pages, jekyll and freenom, everything seems to work but my site is under http. When I try to make https, I get the following message:
"Unavailable for your site because your domain is not properly configured to support HTTPS"

Could you help me solve this problem, please?
Thank you.
Sincerely

**Comment by AnirudhGoel** [comment]
In case you still haven't figured it out, refer to [this](https://medium.com/@goelanirudh/add-https-to-your-namecheap-domain-hosted-on-github-pages-d66fd96308b5) post.
